// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transliteration.Data;

#nullable disable

namespace Transliteration.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Transliteration.Data.Models.NameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameOriginal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameTransliterated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NameOriginal");

                    b.HasIndex("NameTransliterated");

                    b.ToTable("NameEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameOriginal = "Иван",
                            NameTransliterated = "Ivan"
                        },
                        new
                        {
                            Id = 2,
                            NameOriginal = "Мария",
                            NameTransliterated = "Maria"
                        },
                        new
                        {
                            Id = 3,
                            NameOriginal = "Петя",
                            NameTransliterated = "Petya"
                        },
                        new
                        {
                            Id = 4,
                            NameOriginal = "ПламенА",
                            NameTransliterated = "Plamena"
                        },
                        new
                        {
                            Id = 5,
                            NameOriginal = "PLAMENA",
                            NameTransliterated = "Plamena"
                        },
                        new
                        {
                            Id = 6,
                            NameOriginal = "PetyA",
                            NameTransliterated = "Petya"
                        },
                        new
                        {
                            Id = 7,
                            NameOriginal = "Георги",
                            NameTransliterated = "Georgi"
                        },
                        new
                        {
                            Id = 8,
                            NameOriginal = "Georgi",
                            NameTransliterated = "Georgi"
                        },
                        new
                        {
                            Id = 9,
                            NameOriginal = "Daniel",
                            NameTransliterated = "Daniel"
                        },
                        new
                        {
                            Id = 10,
                            NameOriginal = "Даниел",
                            NameTransliterated = "Daniel"
                        },
                        new
                        {
                            Id = 11,
                            NameOriginal = "Yoana",
                            NameTransliterated = "Yoana"
                        },
                        new
                        {
                            Id = 12,
                            NameOriginal = "Йоана",
                            NameTransliterated = "Yoana"
                        },
                        new
                        {
                            Id = 13,
                            NameOriginal = "Кристиян",
                            NameTransliterated = "Kristiyan"
                        },
                        new
                        {
                            Id = 14,
                            NameOriginal = "Martin",
                            NameTransliterated = "Martin"
                        },
                        new
                        {
                            Id = 15,
                            NameOriginal = "Мартин",
                            NameTransliterated = "Martin"
                        },
                        new
                        {
                            Id = 16,
                            NameOriginal = "пЛамЕна",
                            NameTransliterated = "Plamena"
                        },
                        new
                        {
                            Id = 17,
                            NameOriginal = "Kristian",
                            NameTransliterated = "Kristian"
                        },
                        new
                        {
                            Id = 18,
                            NameOriginal = "Кристиан",
                            NameTransliterated = "Kristian"
                        },
                        new
                        {
                            Id = 19,
                            NameOriginal = "SimeoN",
                            NameTransliterated = "Simeon"
                        },
                        new
                        {
                            Id = 20,
                            NameOriginal = "Симеон",
                            NameTransliterated = "Simeon"
                        },
                        new
                        {
                            Id = 21,
                            NameOriginal = "Александър",
                            NameTransliterated = "Aleksandar"
                        },
                        new
                        {
                            Id = 22,
                            NameOriginal = "Aleksandar",
                            NameTransliterated = "Aleksandar"
                        },
                        new
                        {
                            Id = 23,
                            NameOriginal = "София",
                            NameTransliterated = "Sofia"
                        },
                        new
                        {
                            Id = 24,
                            NameOriginal = "Sofia",
                            NameTransliterated = "Sofia"
                        },
                        new
                        {
                            Id = 25,
                            NameOriginal = "НикоЛ",
                            NameTransliterated = "Nikol"
                        },
                        new
                        {
                            Id = 26,
                            NameOriginal = "Илия",
                            NameTransliterated = "Ilia"
                        },
                        new
                        {
                            Id = 27,
                            NameOriginal = "Ilia",
                            NameTransliterated = "Ilia"
                        },
                        new
                        {
                            Id = 28,
                            NameOriginal = "Виктория",
                            NameTransliterated = "Viktoria"
                        },
                        new
                        {
                            Id = 29,
                            NameOriginal = "Viktoria",
                            NameTransliterated = "Viktoria"
                        },
                        new
                        {
                            Id = 30,
                            NameOriginal = "IvaylA",
                            NameTransliterated = "Ivayla"
                        });
                });

            modelBuilder.Entity("Transliteration.Data.Models.SearchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SearchLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
