CREATE DATABASE IF NOT EXISTS NewsSiteDB;
USE NewsSiteDB;

CREATE TABLE NewsCategories
(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    CategoryName VARCHAR(50) NOT NULL
);

CREATE TABLE Roles
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    RoleName VARCHAR(50) NOT NULL
);

CREATE TABLE Editors
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    EditorName VARCHAR(100) NOT NULL
);

CREATE TABLE News
(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(50) NOT NULL,
    Content VARCHAR(255) NOT NULL,
    DateOfCreation DATE NOT NULL,
    EditorId INT NOT NULL,
    CategoryId INT NOT NULL,
    
    CONSTRAINT FOREIGN KEY (EditorId) REFERENCES Editors(Id),
    CONSTRAINT FOREIGN KEY (CategoryId) REFERENCES NewsCategories(Id)
);

CREATE TABLE Users
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    RoleId INT NOT NULL,
    IsRegistered BIT NOT NULL,
    `Name` VARCHAR(255) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Username VARCHAR(50) NOT NULL,
	`Password` VARCHAR(50) NOT NULL,
    
    CONSTRAINT FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE Comments
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Content VARCHAR(255) NOT NULL,
	DateOfCreation DATE NOT NULL,
    CreatorId INT NOT NULL,
    NewsId INT NOT NULL,
    
    CONSTRAINT FOREIGN KEY (CreatorId) REFERENCES Users(Id),
    CONSTRAINT FOREIGN KEY (NewsId) REFERENCES News(Id)
);

CREATE TABLE Media
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    URL VARCHAR(255) NOT NULL,
    NewsId INT NOT NULL,
    
    CONSTRAINT FOREIGN KEY (NewsId) REFERENCES News(Id)
);



