DROP DATABASE IF EXISTS CinemaProjections;
CREATE DATABASE CinemaProjections;
USE CinemaProjections;

CREATE TABLE Cinemas
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Address VARCHAR(100) NOT NULL
);

CREATE TABLE Halls
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Status VARCHAR(100) NOT NULL,
    CinemaId INT NOT NULL,
    
    CONSTRAINT FOREIGN KEY (CinemaId) REFERENCES Cinemas(Id)
);

CREATE TABLE Films
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Genre VARCHAR(100) NOT NULL,
    Director VARCHAR(100) NOT NULL,
    DateOfCreation DATE NOT NULL,
    Country VARCHAR(100) NOT NULL
);

CREATE TABLE Projections
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	BroadcastTime TIME NOT NULL,
    DurationTime TIME NOT NULL,
    VisitorsCount INT NOT NULL,
    HallId INT NOT NULL,
    FilmId INT NOT NULL,
    
    CONSTRAINT FOREIGN KEY (HallId) REFERENCES Halls(Id),
    CONSTRAINT FOREIGN KEY (FilmId) REFERENCES Films(Id)
);

